config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  root 'posts#index'

  resources :posts do
    collection do
      get '/page_scroll' => 'posts#page_scroll', as: 'scroll'
    end
  end

end

app/models/post.rb
class Post < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.order("created_at DESC").page(params[:page])
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  
  def page_scroll
    @posts = Post.order("created_at DESC").page(params[:page])
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :contents)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/_footer.html.erb
<!-- Footer -->
<footer>
  <div class="container">
    <div class="row">
      <div class="col-lg-8 col-md-10 mx-auto">
        <ul class="list-inline text-center">
          <li class="list-inline-item">
            <a href="#">
              <span class="fa-stack fa-lg">
                <i class="fa fa-circle fa-stack-2x"></i>
                <i class="fa fa-twitter fa-stack-1x fa-inverse"></i>
              </span>
            </a>
          </li>
          <li class="list-inline-item">
            <a href="#">
              <span class="fa-stack fa-lg">
                <i class="fa fa-circle fa-stack-2x"></i>
                <i class="fa fa-facebook fa-stack-1x fa-inverse"></i>
              </span>
            </a>
          </li>
          <li class="list-inline-item">
            <a href="#">
              <span class="fa-stack fa-lg">
                <i class="fa fa-circle fa-stack-2x"></i>
                <i class="fa fa-github fa-stack-1x fa-inverse"></i>
              </span>
            </a>
          </li>
        </ul>
        <p class="copyright text-muted">Copyright &copy; jjuya's 2017</p>
      </div>
    </div>
  </div>
</footer>

app/views/layouts/_nav.html.erb
<!-- Navigation -->
<nav class="navbar navbar-expand-lg navbar-light fixed-top" id="mainNav">
  <div class="container">
      <%= link_to "JJu POSTS", root_path, class: "navbar-brand" %>
    <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
      Menu
      <i class="fa fa-bars"></i>
    </button>
    <div class="collapse navbar-collapse" id="navbarResponsive">
      <ul class="navbar-nav ml-auto">
        <li class="nav-item">
            <%= link_to "Home", root_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "New Post", new_post_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
            <% if user_signed_in? %>
                <%= link_to "Log Out", destroy_user_session_path, method: :delete, data: {confirm: "로그아웃 하시겠습니까?"}, class: "nav-link" %>
            <% else %>
                <%= link_to "Log In", new_user_session_path, class: "nav-link" %>
            <% end %>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Workspace</title>
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  
  <%= render '/layouts/nav'%>

<%= yield %>

  <%= render '/layouts/footer'%>

</body>
</html>

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :contents %><br>
    <%= f.text_area :contents %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<!-- Page Header -->
<header class="masthead" style="background-image: url(<%= asset_path 'contact-bg.jpg' %>">
  <div class="overlay"></div>
  <div class="container">
    <div class="row">
      <div class="col-lg-8 col-md-10 mx-auto">
        <div class="page-heading">
          <h1>Edit Post</h1>
          <span class="subheading">Edit Your Post</span>
        </div>
      </div>
    </div>
  </div>
</header>

<!-- Main Content -->
<div class="container">
  <div class="row">
    <div class="col-lg-8 col-md-10 mx-auto">
      <p>Edit Your Posts!</p>
      
      <%= form_for(@post, id: "contactForm") do |f| %>
        <div class="control-group">
          <div class="form-group floating-label-form-group controls">
            <%= f.label :title %>
            <%= f.text_field :title, class: "form-control", value: "#{@post.title}" %>
            <!--<input type="text" class="form-control" placeholder="Name" id="name" required data-validation-required-message="Please enter title.">-->
            <p class="help-block text-danger"></p>
          </div>
        </div>
        <div class="control-group">
          <div class="form-group floating-label-form-group controls">
            <%= f.label :contents %>
            <%= f.text_area :contents, size: "24x5", class: "form-control", value: "#{@post.contents}" %>
            
            <!--<textarea rows="5" class="form-control" placeholder="Message" id="message" required data-validation-required-message="Please enter a message."></textarea>-->
            <p class="help-block text-danger"></p>
          </div>
        </div>
        <br>
        <div id="success"></div>
        <div class="form-group">
            <%= submit_tag("Submit", class: "btn btn-primary", id: "sendMessageButton") %>
          <!--<button type="submit" class="btn btn-primary" id="sendMessageButton">Send</button>-->
        </div>
      <% end %>
    </div>
  </div>
</div>

<hr>

app/views/posts/index.html.erb
<!-- Page Header -->
<header class="masthead" style="background-image: url(<%= asset_path 'home-bg.jpg' %>)">
  <div class="overlay"></div>
  <div class="container">
    <div class="row">
      <div class="col-lg-8 col-md-10 mx-auto">
        <div class="site-heading">
          <h1>JJu POSTS</h1>
          <span class="subheading">Bootstrap Theme class</span>
        </div>
      </div>
    </div>
  </div>
</header>

<!-- Main Content -->
<div class="container">
  <div class="row">
    <div class="col-lg-8 col-md-10 mx-auto" id="posts_index">
      <% @posts.each do |post| %>
        <div class="post-preview">
          <a href="<%= post_path(post) %>">
            <h2 class="post-title">
              <%= post.title %>
            </h2>
            <h3 class="post-subtitle">
                <%= truncate post.contents, length: 50 %>
            </h3>
          </a>
          <p class="post-meta">Posted by
            <a href="<%= post_path(post) %>">Start Bootstrap</a>
            <%= post.created_at.to_s(:short)%></p>
        </div>
        <hr>
      <% end %>
    </div>
  </div>
</div>

<script>
  $(function() {
    var page_scroll_index = 2;
    
    $(document).on('scroll', function(){
  	  // 진짜 중요한거!!!!!
  	  if($(window).scrollTop() >= $(document).height() - $(window).height()) {
  	    $.ajax({
  	      method: "GET",
          url: "<%= scroll_posts_path %>",
          data: {
            page: page_scroll_index++
          }
  	    })
  	  }
    });
  });
</script>

app/views/posts/new.html.erb
<!-- Page Header -->
<header class="masthead" style="background-image: url(<%= asset_path 'contact-bg.jpg' %>">
  <div class="overlay"></div>
  <div class="container">
    <div class="row">
      <div class="col-lg-8 col-md-10 mx-auto">
        <div class="page-heading">
          <h1>New Post</h1>
          <span class="subheading">Create New Your Post</span>
        </div>
      </div>
    </div>
  </div>
</header>

<!-- Main Content -->
<div class="container">
  <div class="row">
    <div class="col-lg-8 col-md-10 mx-auto">
      <p>Create Your Posts!</p>
      
      <%= form_for(@post, id: "contactForm") do |f| %>
        <div class="control-group">
          <div class="form-group floating-label-form-group controls">
            <label>Title</label>
            <%= f.label :title %>
            <%= f.text_field :title, class: "form-control", placeholder: "title" %>
            <!--<input type="text" class="form-control" placeholder="Name" id="name" required data-validation-required-message="Please enter title.">-->
            <p class="help-block text-danger"></p>
          </div>
        </div>
        <div class="control-group">
          <div class="form-group floating-label-form-group controls">
            <%= f.label :contents %>
            <%= f.text_area :contents, size: "24x5", class: "form-control", placeholder: "contents" %>
            
            <!--<textarea rows="5" class="form-control" placeholder="Message" id="message" required data-validation-required-message="Please enter a message."></textarea>-->
            <p class="help-block text-danger"></p>
          </div>
        </div>
        <br>
        <div id="success"></div>
        <div class="form-group">
            <%= submit_tag("Submit", class: "btn btn-primary", id: "sendMessageButton") %>
          <!--<button type="submit" class="btn btn-primary" id="sendMessageButton">Send</button>-->
        </div>
      <% end %>
    </div>
  </div>
</div>

<hr>

app/views/posts/page_scroll.js.erb
$('#posts_index').append(
`
<% @posts.each do |post| %>
    <div class="post-preview">
      <a href="<%= post_path(post) %>">
        <h2 class="post-title">
          <%= post.title %>
        </h2>
        <h3 class="post-subtitle">
            <%= truncate post.contents, length: 50 %>
        </h3>
      </a>
      <p class="post-meta">Posted by
        <a href="<%= post_path(post) %>">Start Bootstrap</a>
        <%= post.created_at.to_s(:short)%></p>
    </div>
    <hr>
<% end %>
`
);

app/views/posts/show.html.erb
<!-- Page Header -->
<header class="masthead" style="background-image: url('img/post-bg.jpg')">
  <div class="overlay"></div>
  <div class="container">
    <div class="row">
      <div class="col-lg-8 col-md-10 mx-auto">
        <div class="post-heading">
          <h1><%= @post.title %></h1>
          <h2 class="subheading">Problems look mighty small from 150 miles up</h2>
          <span class="meta">Posted by
            <a href="#">Start Bootstrap</a>
            <%= @post.created_at.to_s(:long) %></span>
        </div>
      </div>
    </div>
  </div>
</header>

<!-- Post Content -->
<article>
  <div class="container">
    <div class="row">
      <div class="col-lg-8 col-md-10 mx-auto">
        <h2 class="section-heading">The Final Frontier</h2>
        <blockquote class="blockquote">The dreams of yesterday are the hopes of today and the reality of tomorrow. Science has not yet mastered prophecy. We predict too much for the next year and yet far too little for the next ten.</blockquote>
        
        <%= @post.contents %>
        
        <p></p>
      </div>
    </div>
    
    <div class="row">
      <div class="col-lg-8 col-md-10 mx-auto">
        <div class="text-right">
          <%= link_to "Edit", edit_post_path(@post), class: "btn btn-primary" %>
          <%= link_to "Delete", post_path(@post), method: :delete, class: "btn btn-danger" %>
        </div>  
      </div>
    </div>
     
    
  </div>
</article>

<hr>